version: "3.7"

services:

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "30001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test

  db:
    image: postgres
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: proiectpass
      POSTGRES_DB: proiectpw
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    ports:
      - "54328:5432"
    volumes:
      - proiect_pgdb:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  proiect_pgdb:
